// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */
enum TerrainType {
  Grass,
  Water,
  Forest,
  Mountain,
  Sand,
  Village
}

enum ElementType {
  Water,
  Fire,
  Earth,
  Air
}

enum SizeType {
  Small,
  Medium,
  Large
}
