// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Battle } from "./../../battle.sol";

interface ICombatSystem {
  function startBattle(bytes32 entityA, bytes32 entityB) external returns (Battle);
}
