// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IMoveSystem {
    function move(uint32 x, uint32 y) external;

    function spawn(uint32 x, uint32 y) external;
}
