// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface INftSystem {
  function entityOwner(uint256 entityId) external view returns (address);

  function mint(address to, bytes32 entityId) external;

  function burn(uint256 entityId) external;

  function transferFrom(address from, address to, uint256 entityId) external;
}
