// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { ShopInventory } from "./../../shop_inventory.sol";

interface IShopSystem {
  function buy(uint256 monsterType) external payable returns (bytes32);

  function getInventory() external view returns (ShopInventory);
}
